## Array Attributes

In [3]:
import numpy as np

x = np.array([[2,3,4],[7,8,3],[4,5,6]])
print(x)

[[2 3 4]
 [7 8 3]
 [4 5 6]]


In [11]:
# check attributes of array after you load array from file (here dummy eg)
print('dimensions - ',x.ndim)
print('shape - ',x.shape)
print('size - ',x.size)
print('data_type - ',x.dtype)
print('memory in bytes - ',x.nbytes)

dimensions -  2
shape -  (3, 3)
size -  9
data_type -  int64
memory in bytes -  72
