## Array indexing, slicing and filtering

In [5]:
import numpy as np
import os

os.getcwd()

data = np.loadtxt(fname='/Users/sylvia/Desktop/IITR/python/Data/patient_data.csv',delimiter=',')


In [9]:
# Shape, size and datatype
print(data.shape)
print(data.size)
print(data.dtype)

(60, 40)
2400
float64


## Indexing
Refer elements in array using index
In list also we access elements using index, however in arrays we have dimensions concept also.

In [11]:
# access 1st element in this data (this is 2-D data)
print('first element',data[0][0])
print('second element',data[0][1])

first element 0.0
second element 0.0


## Slicing

In [16]:
# Extract data for first 4 patients only
p_data = data[:4,]   # by default assumes all columns
                     # or can write data[0:4,:]  i.e. first 4 rows and all cols
print(p_data)

[[ 0.  0.  1.  3.  1.  2.  4.  7.  8.  3.  3.  3. 10.  5.  7.  4.  7.  7.
  12. 18.  6. 13. 11. 11.  7.  7.  4.  6.  8.  8.  4.  4.  5.  7.  3.  4.
   2.  3.  0.  0.]
 [ 0.  1.  2.  1.  2.  1.  3.  2.  2.  6. 10. 11.  5.  9.  4.  4.  7. 16.
   8.  6. 18.  4. 12.  5. 12.  7. 11.  5. 11.  3.  3.  5.  4.  4.  5.  5.
   1.  1.  0.  1.]
 [ 0.  1.  1.  3.  3.  2.  6.  2.  5.  9.  5.  7.  4.  5.  4. 15.  5. 11.
   9. 10. 19. 14. 12. 17.  7. 12. 11.  7.  4.  2. 10.  5.  4.  2.  2.  3.
   2.  2.  1.  1.]
 [ 0.  0.  2.  0.  4.  2.  2.  1.  6.  7. 10.  7.  9. 13.  8.  8. 15. 10.
  10.  7. 17.  4.  4.  7.  6. 15.  6.  4.  9. 11.  3.  5.  6.  3.  3.  4.
   2.  3.  2.  1.]]


In [18]:
# Extract data for all patients for 1st week (7 days)

c_data = data[:,0:7]
print(c_data)

[[0. 0. 1. 3. 1. 2. 4.]
 [0. 1. 2. 1. 2. 1. 3.]
 [0. 1. 1. 3. 3. 2. 6.]
 [0. 0. 2. 0. 4. 2. 2.]
 [0. 1. 1. 3. 3. 1. 3.]
 [0. 0. 1. 2. 2. 4. 2.]
 [0. 0. 2. 2. 4. 2. 2.]
 [0. 0. 1. 2. 3. 1. 2.]
 [0. 0. 0. 3. 1. 5. 6.]
 [0. 1. 1. 2. 1. 3. 5.]
 [0. 1. 0. 0. 4. 3. 3.]
 [0. 1. 0. 0. 3. 4. 2.]
 [0. 0. 2. 1. 4. 3. 6.]
 [0. 0. 0. 0. 1. 3. 1.]
 [0. 1. 2. 1. 1. 1. 4.]
 [0. 1. 1. 0. 1. 2. 4.]
 [0. 0. 0. 0. 2. 3. 6.]
 [0. 0. 0. 1. 2. 1. 4.]
 [0. 0. 2. 1. 2. 5. 4.]
 [0. 1. 2. 0. 1. 4. 3.]
 [0. 1. 1. 3. 1. 4. 4.]
 [0. 0. 2. 3. 2. 3. 2.]
 [0. 0. 0. 3. 4. 5. 1.]
 [0. 1. 1. 1. 1. 3. 3.]
 [0. 1. 1. 1. 2. 3. 5.]
 [0. 0. 2. 1. 3. 3. 2.]
 [0. 0. 1. 2. 4. 2. 2.]
 [0. 0. 1. 1. 1. 5. 1.]
 [0. 0. 2. 2. 3. 4. 6.]
 [0. 0. 0. 1. 4. 4. 6.]
 [0. 1. 1. 0. 3. 2. 4.]
 [0. 0. 2. 3. 3. 4. 5.]
 [0. 1. 2. 2. 2. 3. 6.]
 [0. 0. 2. 1. 3. 5. 6.]
 [0. 0. 1. 2. 4. 1. 5.]
 [0. 0. 0. 3. 1. 3. 6.]
 [0. 1. 2. 2. 2. 5. 5.]
 [0. 1. 1. 2. 3. 1. 5.]
 [0. 1. 0. 3. 2. 4. 1.]
 [0. 1. 1. 3. 1. 1. 5.]
 [0. 0. 0. 2. 2. 1. 3.]
 [0. 0. 1. 3. 3.

In [21]:
# Extract data of patients 5 to 10 for second week

e_data = data[5:10,6:13]
print(e_data)

[[ 2.  1.  6.  4.  7.  6.  6.]
 [ 2.  5.  5.  8.  6.  5. 11.]
 [ 2.  3.  5.  3.  7.  8.  8.]
 [ 6.  5.  5.  8.  2.  4. 11.]
 [ 5.  3.  5.  8.  6.  8. 12.]]


## Filtering
Filtering is used to get specific values from an array.
This is not just slicing data, this is extracting based on condition


In [23]:
# Extract reading only above 10 for all patients
print(data>10)    # returns array of booleans which satisfies this condition

[[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]]


In [24]:
print(data[data>10])

[12. 18. 13. 11. 11. 11. 16. 18. 12. 12. 11. 11. 15. 11. 19. 14. 12. 17.
 12. 11. 13. 15. 17. 15. 11. 17. 14. 13. 12. 15. 16. 18. 12. 12. 18. 12.
 11. 13. 12. 17. 15. 13. 15. 11. 18. 19. 20. 13. 15. 11. 12. 11. 17. 11.
 16. 12. 14. 13. 11. 12. 13. 13. 16. 18. 15. 16. 14. 12. 11. 13. 13. 15.
 18. 15. 15. 16. 11. 14. 12. 11. 14. 11. 11. 16. 18. 12. 11. 12. 17. 13.
 15. 13. 12. 12. 13. 13. 16. 15. 11. 11. 11. 12. 13. 17. 12. 13. 12. 18.
 17. 12. 11. 11. 11. 14. 11. 11. 12. 12. 13. 19. 14. 17. 13. 11. 12. 12.
 14. 14. 13. 19. 12. 13. 11. 11. 15. 17. 11. 12. 12. 13. 12. 13. 11. 13.
 16. 19. 16. 11. 14. 12. 11. 12. 12. 15. 13. 18. 19. 11. 12. 12. 12. 12.
 16. 14. 12. 12. 14. 17. 13. 16. 15. 13. 12. 13. 14. 11. 15. 14. 13. 13.
 14. 11. 12. 12. 15. 17. 16. 15. 11. 12. 12. 16. 17. 11. 14. 13. 11. 12.
 12. 12. 13. 13. 15. 12. 18. 14. 16. 12. 11. 14. 15. 12. 15. 15. 13. 17.
 11. 11. 12. 19. 20. 18. 14. 12. 17. 16. 14. 15. 17. 14. 13. 12. 11. 11.
 14. 14. 12. 16. 13. 15. 13. 14. 19. 15. 15. 11. 11