## Different ways of creating Numpy array

### Single dimension numpy array

In [35]:
import numpy as np

# create a one dimension array (constructor np.array)
x = np.array([33,89,56,0])
print(x)
print((type(x)))


[33 89 56  0]
<class 'numpy.ndarray'>


### Multi dimension numpy array

In [36]:
# create multidimensional array - 2d array
y = np.array([[1,2,3],[10,11,12]])
print(y)
print(type(y))


[[ 1  2  3]
 [10 11 12]]
<class 'numpy.ndarray'>


In [49]:
# create multidimensional array - 3d array
z = np.array([[[2,3,4],[5,6,7]],[[9,8,3],[3,4,7]]])
print(z)
print(type(z))

[[[2 3 4]
  [5 6 7]]

 [[9 8 3]
  [3 4 7]]]
<class 'numpy.ndarray'>


## Creating numeric ranges
1. arange
2. linspace
3. logspace

linspace and logspace application is purely mathematical.

In [38]:
a = np.arange(0, 1000)
print(a)
type(a)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

numpy.ndarray

In [39]:
b = np.arange(0, 1000, 10)
print(b)

[  0  10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170
 180 190 200 210 220 230 240 250 260 270 280 290 300 310 320 330 340 350
 360 370 380 390 400 410 420 430 440 450 460 470 480 490 500 510 520 530
 540 550 560 570 580 590 600 610 620 630 640 650 660 670 680 690 700 710
 720 730 740 750 760 770 780 790 800 810 820 830 840 850 860 870 880 890
 900 910 920 930 940 950 960 970 980 990]


In [40]:
# linspace & logspace give us an array in a linear space or a logarithmic space.
# space means dimensions we are working on meaning linear scale or logarithmic scale.

z = np.linspace(0,1000,10)   #start, stop, count
print('linspace', z)

z1 = np.logspace(0,1,10)
print('logspace',z1)

linspace [   0.          111.11111111  222.22222222  333.33333333  444.44444444
  555.55555556  666.66666667  777.77777778  888.88888889 1000.        ]
logspace [ 1.          1.29154967  1.66810054  2.15443469  2.7825594   3.59381366
  4.64158883  5.9948425   7.74263683 10.        ]


## Creating Special arrays
### useful in linear algebra, for calculation with matrices
1. Ones
2. Zeroes
3. array with specific number
4. identity matrix
5. random matrix

In [50]:
array_zero1 = np.zeros(shape=5)
print('array_1-D\n',array_zero1,'\n')

array_zero2 = np.zeros(shape=(5,2))
print('array_2-D\n',array_zero2,'\n')

array_zero3 = np.zeros(shape=(5,2,4))
print('array_3-D\n',array_zero3,'\n')

## This means we have 5 (2 dimensional arrays) and each 2 dimensional array has 2 elements/rows/observations of 4 columns each(2*4)

## 5 is the 3rd dimension and we know 3 dimension array consists of 2 dimensional arrays so number 5 means that in count there are 5 (2 dimensional arrays)
## 2 is the 2nd dimension and says that each of 2 dimensional array has 2 elements inside it and 2 dimensional array consists of 1D arrays so
### 4 represents 1st dimension and number 4 represents has 4 elements inside it.


array_1-D
 [0. 0. 0. 0. 0.] 

array_2-D
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]] 

array_3-D
 [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]] 



In [42]:
print('dim',array_zero3.ndim)
print('shape',array_zero3.shape)

dim 3
shape (5, 2, 4)


In [43]:
array_ones = np.ones(shape=(3,2))
print(array_ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [44]:
# creating a matrix with specific number

array_eight = np.full(shape=(3,2),fill_value=8)
print(array_eight)

[[8 8]
 [8 8]
 [8 8]]


In [45]:
# create identity matrix (all elements 0 except diagonal which are 1)
# identity matrix is always a square matrix

array_i = np.identity(3)
print(array_i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [46]:
# matrix of random numbers
# suppose when u r simulating u might need to use random numbers

array_rand = np.random.rand(3,2)
print(array_rand)

[[0.72985799 0.56122244]
 [0.34092828 0.87694946]
 [0.69408893 0.92714871]]


In [47]:
array_randint = np.random.randint(-9,9,size=(3,2))   # randint(low,high,size)
print(array_randint)

[[-4 -3]
 [-7 -7]
 [-5 -2]]


In [48]:
# from files loadtxt (this function although txt can be used for csv file)
# delimiter in csv is comma, likewise others can be tab etc
# this loads data from csv file to a numpy array, then can manipulate, work on this data

data = np.loadtxt(fname='telco.csv',delimiter=',')
print(data)

[[0.00000e+00 1.00000e+00 2.98500e+01 2.98500e+01]
 [0.00000e+00 3.40000e+01 5.69500e+01 1.88950e+03]
 [0.00000e+00 2.00000e+00 5.38500e+01 1.08150e+02]
 [0.00000e+00 4.50000e+01 4.23000e+01 1.84075e+03]
 [0.00000e+00 2.00000e+00 7.07000e+01 1.51650e+02]
 [0.00000e+00 8.00000e+00 9.96500e+01 8.20500e+02]
 [0.00000e+00 2.20000e+01 8.91000e+01 1.94940e+03]
 [0.00000e+00 1.00000e+01 2.97500e+01 3.01900e+02]
 [0.00000e+00 2.80000e+01 1.04800e+02 3.04605e+03]
 [0.00000e+00 6.20000e+01 5.61500e+01 3.48795e+03]
 [0.00000e+00 1.30000e+01 4.99500e+01 5.87450e+02]
 [0.00000e+00 1.60000e+01 1.89500e+01 3.26800e+02]
 [0.00000e+00 5.80000e+01 1.00350e+02 5.68110e+03]
 [0.00000e+00 4.90000e+01 1.03700e+02 5.03630e+03]
 [0.00000e+00 2.50000e+01 1.05500e+02 2.68605e+03]
 [0.00000e+00 6.90000e+01 1.13250e+02 7.89515e+03]
 [0.00000e+00 5.20000e+01 2.06500e+01 1.02295e+03]
 [0.00000e+00 7.10000e+01 1.06700e+02 7.38225e+03]
 [0.00000e+00 1.00000e+01 5.52000e+01 5.28350e+02]]
