## Array Operations

In numpy, arithmetic operations are always applied element wise. It will effect every element of array.

In [1]:
import numpy as np

data = np.loadtxt(fname='/Users/sylvia/Desktop/IITR/python/Data/patient_data.csv',delimiter=',')
type(data)

numpy.ndarray

In [2]:
patient_1 = data[0,]
print(patient_1)
type(patient_1)

[ 0.  0.  1.  3.  1.  2.  4.  7.  8.  3.  3.  3. 10.  5.  7.  4.  7.  7.
 12. 18.  6. 13. 11. 11.  7.  7.  4.  6.  8.  8.  4.  4.  5.  7.  3.  4.
  2.  3.  0.  0.]


numpy.ndarray

## Basic Mathematical functions

In [6]:
# Mathematical operations, original array will remain unchanged.

# 1. addition
print('addition\n',patient_1+2)

# 2. subtraction
print('subtraction\n',patient_1-2)

# 3. multiplication
print('multiply\n',patient_1*2)

# 4. division
print('divide\n',patient_1/2)


addition
 [ 2.  2.  3.  5.  3.  4.  6.  9. 10.  5.  5.  5. 12.  7.  9.  6.  9.  9.
 14. 20.  8. 15. 13. 13.  9.  9.  6.  8. 10. 10.  6.  6.  7.  9.  5.  6.
  4.  5.  2.  2.]
subtraction
 [-2. -2. -1.  1. -1.  0.  2.  5.  6.  1.  1.  1.  8.  3.  5.  2.  5.  5.
 10. 16.  4. 11.  9.  9.  5.  5.  2.  4.  6.  6.  2.  2.  3.  5.  1.  2.
  0.  1. -2. -2.]
multiply
 [ 0.  0.  2.  6.  2.  4.  8. 14. 16.  6.  6.  6. 20. 10. 14.  8. 14. 14.
 24. 36. 12. 26. 22. 22. 14. 14.  8. 12. 16. 16.  8.  8. 10. 14.  6.  8.
  4.  6.  0.  0.]
divide
 [0.  0.  0.5 1.5 0.5 1.  2.  3.5 4.  1.5 1.5 1.5 5.  2.5 3.5 2.  3.5 3.5
 6.  9.  3.  6.5 5.5 5.5 3.5 3.5 2.  3.  4.  4.  2.  2.  2.5 3.5 1.5 2.
 1.  1.5 0.  0. ]


## Linear Algebra Functions - We can do matrix calculations
### Matrix multiplication
Matrix multiplication is complicated cz we need to be aware of dimensions as well.

In [13]:
a = np.ones((2,3))
b = np.full(shape=(3,2),fill_value=2)
print(a,'\n\n',b)

[[1. 1. 1.]
 [1. 1. 1.]] 

 [[2 2]
 [2 2]
 [2 2]]


In [15]:
m_mul = np.matmul(a,b)
print(m_mul)

[[6. 6.]
 [6. 6.]]


### Determinant

In [17]:
c = data[3:5,3:5]   # Slicing from original array data
print(c)

[[0. 4.]
 [3. 3.]]


In [18]:
det = np.linalg.det(c)
det

-12.0

## Linear algebra numpy library documentation
### Reference - https://numpy.org/doc/stable/reference/routines.linalg.html

## Statistical Functions

In [21]:
# max & min reading in patient data

print('max',np.max(data))
print('min',np.min(data))

max 20.0
min 0.0


In [23]:
# max reading among first 5 patients
print('max among first 5 patients',np.max(data[0:5]))

max among first 5 patients 19.0


In [27]:
# maximum inflation for patient 10
print(np.max(data[9,]))

18.0


### Using Axis
axis=0, moving along rows gives u statistics of each column<br>
axis=1, moving along columns gives u statistics of each row

In [30]:
# to find max inflation of each patient (each row)
print(np.max(data, axis=1))   # moving along columns gives u max of each row


[18. 18. 19. 17. 17. 18. 17. 20. 17. 18. 18. 18. 17. 16. 17. 18. 19. 19.
 17. 19. 19. 16. 17. 15. 17. 17. 18. 17. 20. 17. 16. 19. 15. 15. 19. 17.
 16. 17. 19. 16. 18. 19. 16. 19. 18. 16. 19. 15. 16. 18. 14. 20. 17. 15.
 17. 16. 17. 19. 18. 18.]


In [32]:
# to find max reading for a particular day (we have 40 days, 40 columns)
print(np.max(data, axis=0))   # moving along rows gives u max of each column.


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 19. 18. 17. 16. 15. 14. 13. 12. 11. 10.  9.  8.  7.  6.  5.
  4.  3.  2.  1.]


In [36]:
# Calculate day wise (here col's represent day) mean or median and std dev of readings
# to find statistics for columns we need to move along rows axis=0
c_mean = np.median(data, axis=0)
print('median\n',c_mean)

c_std = np.std(data, axis=0)
print('\nstd\n',c_std)

median
 [ 0.   0.   1.   2.   2.   3.   4.   4.   5.   6.   6.   5.5  9.5  8.
  8.  10.   8.5 11.  11.5 13.  14.  13.  11.  10.  10.5  9.  10.   7.
  7.   7.   6.   6.   5.   4.   3.   4.   2.   1.   1.   1. ]

std
 [0.         0.49749372 0.73238575 1.05869416 1.1308797  1.37628728
 1.71075032 1.95014244 1.9267128  2.26194361 2.74119803 2.50798724
 3.13488437 3.0922843  3.75040739 4.02285139 3.82226663 3.54008788
 3.94701012 4.50120354 4.24116729 4.54960316 4.19907397 4.09945796
 3.7103459  3.60863163 3.21364279 2.77863876 2.68121034 3.19526559
 2.5157283  2.10890967 1.62369606 1.78138523 1.76351921 1.38283123
 1.11790976 1.161895   0.8055364  0.49553562]
