## Array Transformations
### When we r dealing with linear algebra many times we need to resize, reshape, flatten, transpose array etc

1. reshape
2. resize
3. flatten
4. transpose

Only resize option change original array, none of other options change original array so if u need to use modified array obtained from reshape, flatten or transpose to need to store it to a new variable or assign it to same variable again.

In [39]:
import numpy as np

a = np.array(range(10))
print('1-D array\n',a)

# Need to reshape this 1-D array to 2-D array with 2 rows and 5 columns
b = a.reshape(2,5)  # it does not change original array a, need to assign to new variable
print('\nreshaped 2-D array\n',b)

print('\noriginal array remains unchanged\n',a)

1-D array
 [0 1 2 3 4 5 6 7 8 9]

reshaped 2-D array
 [[0 1 2 3 4]
 [5 6 7 8 9]]

original array remains unchanged
 [0 1 2 3 4 5 6 7 8 9]


In [21]:
## If we need original array to be transformed we use resize instead of reshape
a = np.array(range(10))
print('1-D array\n',a)

a.resize(2,5)
print('\n1-D original array transformed\n',a)

1-D array
 [0 1 2 3 4 5 6 7 8 9]

1-D original array transformed
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [37]:
# flatten function (any dimensional array will always be converted to 1-D array)
x = np.array([[3,4,5],[9,10,11]])
print('original array\n',x)

print('\nflattened array\n',x.flatten())

print('original array remains unchanged\n',x)

original array
 [[ 3  4  5]
 [ 9 10 11]]

flattened array
 [ 3  4  5  9 10 11]
original array remains unchanged
 [[ 3  4  5]
 [ 9 10 11]]


In [38]:
# transpose (exchange rows and columns)
y = np.array([[3,4,5],[9,10,11]])
print('original array\n',x)

print('\n transposed array\n',y.transpose())

print('\n original array remains unchanged\n',y)
# since original unchanged if u need to use transpose, assign it to new variable or
# assign it to same variable a.


original array
 [[ 3  4  5]
 [ 9 10 11]]

 transposed array
 [[ 3  9]
 [ 4 10]
 [ 5 11]]

 original array remains unchanged
 [[ 3  4  5]
 [ 9 10 11]]


## Stacking arrays (hstack and vstack)
You can stack or combine 2 or more arrays & create 1 single array out of that.

In [40]:
arr = np.array([[0,1,2,3,4],[5,6,7,8,9]])
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


### hstack

In [44]:
# stacked side by side
print(np.hstack((arr,arr)))   # if function takes tuple as i/p, u need to give inside ()

[[0 1 2 3 4 0 1 2 3 4]
 [5 6 7 8 9 5 6 7 8 9]]


### vstack

In [47]:
print(np.vstack((arr,arr)))  # stacked one under the another

[[0 1 2 3 4]
 [5 6 7 8 9]
 [0 1 2 3 4]
 [5 6 7 8 9]]
