In [1]:
# Slicing List
l = [45,90,340,11289]

In [2]:
print(l)

[45, 90, 340, 11289]


In [3]:
type(l)

list

In [4]:
l[1:]

[90, 340, 11289]

In [5]:
l[0:2]

[45, 90]

In [6]:
l[::2]

[45, 340]

In [10]:
# Slicing Arrays
import numpy as np

In [15]:
a = np.array(l)

In [16]:
type(a)

numpy.ndarray

In [17]:
a

array([   45,    90,   340, 11289])

In [18]:
a[2:]

array([  340, 11289])

In [19]:
a[2:4]

array([  340, 11289])

In [20]:
# Whenever u slice an array u do not create a copy of that array
# while with list u r creating another copy so u can work with it 
# seperately.
# U just create a view of an array when working with arrays so if u
# make changes to the slice u r going to make changes to the original
# array

In [21]:
b = a[2:4]

In [22]:
print(b)

[  340 11289]


In [23]:
#Here u have not created another array b but u have created a view of
# array a 

In [24]:
b[0]

340

In [26]:
b[:]

array([  340, 11289])

In [32]:
b[:] = 111

In [34]:
b

array([111, 111])

In [35]:
a

array([ 45,  90, 111, 111])

In [36]:
# if u change something in b the value in original a array also have 
# been changed as shown above 
# So when u r creating slice of an array u r not creating a new array
# u r actually just working with same old array just creating a view
# of that array
# That's just how python/numpy protects memory of computer

In [37]:
# In case we need to create a copy of an array use copy function as below
c = a.copy()

In [38]:
c

array([ 45,  90, 111, 111])

In [39]:
# Now we make changes to c
c[1] = 9

In [40]:
c

array([ 45,   9, 111, 111])

In [41]:
a

array([ 45,  90, 111, 111])

In [42]:
# So as seen above when we create a copy a remains as it is and changes
# in c remain seperately in c and do not affect original array a